export default {
    data: [
        {
            "Ativo": true,
            "Codigo": "1",
            "Nome": "Stella Dalva Marques de Azevedo (RI)",
            "Cnpj": "286.957.206-91",
            "Cns": "634B9747AEB852449DA30A415FB60AA9",
            "SerialHd": "04FEF243",
            "Rua": "Avenida 17 de Dezembro, 475",
            "Numero": null,
            "Complemento": null,
            "Bairro": "Centro",
            "Cidade": "Candeias",
            "Uf": "MG",
            "Cep": "37280-000",
            "Email": "leileto@hotmail.com",
            "Telefone1": null,
            "Telefone2": null,
            "Observacao": null,
            "PagaCri": true,
            "Ranking": 0,
            "Prioridade": 0,
            "NomeWorkflow": "Candeias / MG - Imóveis",
            "Id": 1
        },
        {
            "Ativo": true,
            "Codigo": "2",
            "Nome": "Registro de Imoveis de Mariana",
            "Cnpj": "21.103.411/0001-82",
            "Cns": "CCDB762781D918B6F9A22D7E9C43D652",
            "SerialHd": "766F9E95",
            "Rua": "Rua Direita, 175",
            "Numero": null,
            "Complemento": null,
            "Bairro": "Centro",
            "Cidade": "Mariana",
            "Uf": "MG",
            "Cep": "35420-000",
            "Email": "marianacri@yahoo.com.br",
            "Telefone1": null,
            "Telefone2": null,
            "Observacao": null,
            "PagaCri": true,
            "Ranking": 0,
            "Prioridade": 0,
            "NomeWorkflow": "Mariana / MG - Imóveis",
            "Id": 2
        },
        {
            "Ativo": true,
            "Codigo": "4",
            "Nome": "Cart.Sexto Oficio Reg.Imoveis de Manaus",
            "Cnpj": "07.928.440/0001-52",
            "Cns": "EE39E503B6BEDF0C98C388B7E8589ACA",
            "SerialHd": "1CE05270",
            "Rua": "Rua Belem, 929 - Sala 205",
            "Numero": null,
            "Complemento": null,
            "Bairro": "Adrianopolis",
            "Cidade": "Manaus",
            "Uf": "AM",
            "Cep": "69057-030",
            "Email": "cartorio@6rimanaus.com.br",
            "Telefone1": null,
            "Telefone2": null,
            "Observacao": null,
            "PagaCri": true,
            "Ranking": 0,
            "Prioridade": 0,
            "NomeWorkflow": "Manaus / AM - Imóveis - 6º Serviço Registral",
            "Id": 4
        },
        {
            "Ativo": true,
            "Codigo": "24",
            "Nome": "Oficio de Reg.Imoveis Tarumirim",
            "Cnpj": "09.391.065/0001-80",
            "Cns": "CD4AA78EEF2C2A097AFDF7EFAE7BC1D9",
            "SerialHd": "5C0C1B11",
            "Rua": "Avenida Getúlio Vargas , 250 Loja 3",
            "Numero": null,
            "Complemento": null,
            "Bairro": "Centro",
            "Cidade": "Tarumirim",
            "Uf": "MG",
            "Cep": "35140-000",
            "Email": "marcelorcmcouto@hotmail.com",
            "Telefone1": null,
            "Telefone2": null,
            "Observacao": null,
            "PagaCri": true,
            "Ranking": 0,
            "Prioridade": 0,
            "NomeWorkflow": "Tarumirim / MG - Imóveis",
            "Id": 24
        },
        {
            "Ativo": true,
            "Codigo": "30",
            "Nome": "Registro de Imoveis de Caratinga",
            "Cnpj": "09.412.000/0001-73",
            "Cns": "32B37189D500243B8277718B2EBB9192",
            "SerialHd": "840C6B33",
            "Rua": "Rua Deputado José Augusto Ferreira, 196",
            "Numero": null,
            "Complemento": null,
            "Bairro": "Centro",
            "Cidade": "Caratinga",
            "Uf": "MG",
            "Cep": "35300-016",
            "Email": "cri.caratingamg@gmail.com",
            "Telefone1": null,
            "Telefone2": null,
            "Observacao": null,
            "PagaCri": true,
            "Ranking": 4,
            "Prioridade": 22000,
            "NomeWorkflow": "Caratinga / MG - Imóveis",
            "Id": 30
        },
        {
            "Ativo": true,
            "Codigo": "66",
            "Nome": "Humberto Gomes do Amaral - Muzambinho RI",
            "Cnpj": "669.201.320-87",
            "Cns": "7BD15A6D58DC74207F89CE919FF52782",
            "SerialHd": "D89C2DB6",
            "Rua": "Rua capitao Heleodoro Mariano de Almeida, 1422",
            "Numero": null,
            "Complemento": null,
            "Bairro": "Centro",
            "Cidade": "Muzambinho",
            "Uf": "MG",
            "Cep": "37890-000",
            "Email": "humbertoga20@yahoo.com.br",
            "Telefone1": null,
            "Telefone2": null,
            "Observacao": null,
            "PagaCri": true,
            "Ranking": 0,
            "Prioridade": 0,
            "NomeWorkflow": "Muzambinho / MG - Imóveis",
            "Id": 66
        },
        {
            "Ativo": true,
            "Codigo": "96",
            "Nome": "Oficio do Registro de Imoveis de Brasópolis",
            "Cnpj": "03.277.859/0001-30",
            "Cns": "BD2ECBA368839B7447DB9829BA015E98",
            "SerialHd": "7A44F301",
            "Rua": "Rua Capitão Manoel Gomes, 353",
            "Numero": null,
            "Complemento": null,
            "Bairro": "Centro",
            "Cidade": "Brasópolis",
            "Uf": "MG",
            "Cep": "37530-000",
            "Email": "cartorioribrasopolis@yahoo.com.br",
            "Telefone1": null,
            "Telefone2": null,
            "Observacao": null,
            "PagaCri": true,
            "Ranking": 25,
            "Prioridade": 1000,
            "NomeWorkflow": "Brasópolis / MG - Imóveis",
            "Id": 96
        },
        {
            "Ativo": true,
            "Codigo": "105",
            "Nome": "Registro de Imoveis de Tres Coracoes",
            "Cnpj": "21.404.405/0001-65",
            "Cns": "7F2FC4BE557404798E7AC1DF49EE30A7",
            "SerialHd": "8AF51BB7",
            "Rua": "Rua Joaquim Bento Carvalho, 292",
            "Numero": null,
            "Complemento": null,
            "Bairro": "Centro",
            "Cidade": "Tres Coracoes",
            "Uf": "MG",
            "Cep": "37410-000",
            "Email": "luciano.naves@uol.com.br",
            "Telefone1": null,
            "Telefone2": null,
            "Observacao": null,
            "PagaCri": true,
            "Ranking": 17,
            "Prioridade": 9000,
            "NomeWorkflow": "Três Corações / MG - Imóveis",
            "Id": 105
        },
        {
            "Ativo": true,
            "Codigo": "116",
            "Nome": "Oficio do 2 Registro Imoveis Barbacena",
            "Cnpj": "19.555.143/0001-98",
            "Cns": "031A0D8B9F7E04E38EB55AF2CA1550BD",
            "SerialHd": "549F789F",
            "Rua": "Rua Presidente Kened, 710 L/2",
            "Numero": null,
            "Complemento": null,
            "Bairro": "Centro",
            "Cidade": "Barbacena",
            "Uf": "MG",
            "Cep": "36200-042",
            "Email": "flaviocosta@oi.com.br",
            "Telefone1": null,
            "Telefone2": null,
            "Observacao": null,
            "PagaCri": true,
            "Ranking": 0,
            "Prioridade": 0,
            "NomeWorkflow": "Barbacena / MG - Imóveis - 2º Serviço Registral",
            "Id": 116
        },
        {
            "Ativo": true,
            "Codigo": "119",
            "Nome": "Cartorio de Reg. Imoveis de Perdizes",
            "Cnpj": "05.524.275/0001-48",
            "Cns": "022E17EA8E4B56279362591DE2D4794D",
            "SerialHd": "D04F5AA3",
            "Rua": "Rua Antonio Simoes Borges,245",
            "Numero": null,
            "Complemento": null,
            "Bairro": "Centro",
            "Cidade": "Perdizes",
            "Uf": "MG",
            "Cep": "38170-000",
            "Email": "criperdizes@hotmail.com",
            "Telefone1": null,
            "Telefone2": null,
            "Observacao": null,
            "PagaCri": true,
            "Ranking": 0,
            "Prioridade": 0,
            "NomeWorkflow": "Perdizes / MG - Imóveis",
            "Id": 119
        },
        {
            "Ativo": true,
            "Codigo": "128",
            "Nome": "Oficio de Registro de Imoveis Vespasiano",
            "Cnpj": "14.726.127/0001-05",
            "Cns": "02CF3AA212B27F63C1118824536E406D",
            "SerialHd": "9E2B11FE",
            "Rua": "Rua Dumas Chalitas, 63",
            "Numero": null,
            "Complemento": null,
            "Bairro": "Centro",
            "Cidade": "Vespasiano",
            "Uf": "MG",
            "Cep": "33200-000",
            "Email": "rivespasiano@hotmail.com",
            "Telefone1": null,
            "Telefone2": null,
            "Observacao": null,
            "PagaCri": true,
            "Ranking": 6,
            "Prioridade": 20000,
            "NomeWorkflow": "Vespasiano / MG - Imóveis",
            "Id": 126
        },
        {
            "Ativo": true,
            "Codigo": "132",
            "Nome": "Oficio do 2 RI de Montes Claros",
            "Cnpj": "18.756.812/0001-27",
            "Cns": "AD2E584191559A42C0A3AA6120122A3A",
            "SerialHd": "DC4395A8",
            "Rua": "Avenida Dep.Esteves Rodrigues, 600 S-201",
            "Numero": null,
            "Complemento": null,
            "Bairro": "Centro",
            "Cidade": "Montes Claros",
            "Uf": "MG",
            "Cep": "39400-215",
            "Email": "adm.rizzocg@gmail.com",
            "Telefone1": null,
            "Telefone2": null,
            "Observacao": null,
            "PagaCri": true,
            "Ranking": 2,
            "Prioridade": 24000,
            "NomeWorkflow": "Montes Claros / MG - Imóveis - 2º Serviço Registral",
            "Id": 130
        },
        {
            "Ativo": true,
            "Codigo": "240",
            "Nome": "Oficio Reg.Imoveis Gov.Valadares",
            "Cnpj": "21.077.714/0001-78",
            "Cns": "6E36950E15944681218ED134D85575E3",
            "SerialHd": "6EB46AE3",
            "Rua": "Rua Dom Pedro II, 447",
            "Numero": null,
            "Complemento": null,
            "Bairro": "Centro",
            "Cidade": "Governador Valadares",
            "Uf": "MG",
            "Cep": "35010-090",
            "Email": "registro.imoveisgv@yahoo.com.br",
            "Telefone1": null,
            "Telefone2": null,
            "Observacao": null,
            "PagaCri": true,
            "Ranking": 7,
            "Prioridade": 19000,
            "NomeWorkflow": "Governador Valadares / MG - Imóveis - 1º Serviço Registral",
            "Id": 236
        },
        {
            "Ativo": true,
            "Codigo": "279",
            "Nome": "Cartório Registro de Imóveis de Cássia",
            "Cnpj": "12.128.686/0001-80",
            "Cns": "DA61DBFA824E2AAA6713F4FAA33F4763",
            "SerialHd": "2871C6DE",
            "Rua": "Avenida Antônio Lemos, 243",
            "Numero": null,
            "Complemento": null,
            "Bairro": "Centro",
            "Cidade": "Cassia",
            "Uf": "MG",
            "Cep": "37980-000",
            "Email": "pauloafonsosilveira@hotmail.com",
            "Telefone1": null,
            "Telefone2": null,
            "Observacao": null,
            "PagaCri": true,
            "Ranking": 0,
            "Prioridade": 0,
            "NomeWorkflow": "Cássia / MG - Imóveis",
            "Id": 275
        },
        {
            "Ativo": true,
            "Codigo": "402",
            "Nome": "Cartório de Registro de Imóveis de Passos",
            "Cnpj": "20.916.284/0001-78",
            "Cns": "D5CE87D030E38651560DD175E53E498B",
            "SerialHd": "80C94086",
            "Rua": "Rua Elvira Silveira Coimbra,n° 79",
            "Numero": null,
            "Complemento": null,
            "Bairro": "Centro",
            "Cidade": "Passos",
            "Uf": "MG",
            "Cep": "37900-042",
            "Email": "elpidiofreire@uol.com.br",
            "Telefone1": null,
            "Telefone2": null,
            "Observacao": null,
            "PagaCri": true,
            "Ranking": 3,
            "Prioridade": 23000,
            "NomeWorkflow": "Passos / MG - Imóveis",
            "Id": 398
        },
        {
            "Ativo": true,
            "Codigo": "461",
            "Nome": "José Carlos de Oliveira - Manaus 1° RI",
            "Cnpj": "053.057.802-68",
            "Cns": "40CCCAD2AC57C29035A432356F3C978D",
            "SerialHd": "48A34565",
            "Rua": "Rua Joaquim Sarmento - 418",
            "Numero": null,
            "Complemento": null,
            "Bairro": "Centro",
            "Cidade": "Manaus",
            "Uf": "AM",
            "Cep": "69010-020",
            "Email": "financeiro@1rimanaus.com.br",
            "Telefone1": null,
            "Telefone2": null,
            "Observacao": null,
            "PagaCri": true,
            "Ranking": 1,
            "Prioridade": 25000,
            "NomeWorkflow": "Manaus / AM - Imóveis - 1º Serviço Registral",
            "Id": 458
        }
    ]
}